import re

with open("tests/test_general_audit.py", "r") as f:
    content = f.read()

target = '        from app.cycle.phases.phase5_trading import run_phase5_trading\n    \n        ctx = MagicMock()\n        ctx.cycle_id = "cycle_mut3"\n    \n        decisions = [\n            {"ticker": "MSFT", "action": "BUY", "confidence": 95}\n        ]\n    \n        summary = {"trade_skip_categories": {}}\n    \n        # Allocator fails\n        async def mock_alloc(*args, **kwargs):\n            raise RuntimeError("Allocator crashed")\n    \n        with patch("app.cycle.trading_phase.get_portfolio", return_value={"cash": 10000, "positions": []}), \\\n             patch("app.cycle.trading_phase.check_portfolio_gate", return_value={"blocked": False, "warnings": []}), \\\n             patch("app.cycle.trading_phase.run_portfolio_allocator", new_callable=AsyncMock, side_effect=mock_alloc), \\\n             patch("app.cycle.trading_phase.run_trade_execution", new_callable=AsyncMock, return_value={"decision": "APPROVE", "shares": 0}), \\\n             patch("app.cycle.trading_phase.buy", new_callable=AsyncMock, return_value={"price": 300, "qty": 3, "amount": 900}), \\\n             patch("app.cycle.trading_phase.get_size_pct", return_value=0.10) as mock_size, \\\n             patch("app.cycle.phases.phase5_trading.take_snapshot"):\n    \n            await run_phase5_trading(ctx, "bot1", decisions, MagicMock(), summary, {}, MagicMock())\n    \n        # Should have called fallback sizing\n        assert mock_size.called'

replacement = '        from app.cycle.trading_phase import execute_decisions\n    \n        decisions = [\n            {"ticker": "MSFT", "action": "BUY", "confidence": 95}\n        ]\n    \n        # Allocator fails\n        async def mock_alloc(*args, **kwargs):\n            raise RuntimeError("Allocator crashed")\n    \n        with patch("app.cycle.trading_phase.get_portfolio", return_value={"cash": 10000, "positions": []}), \\\n             patch("app.cycle.trading_phase.check_portfolio_gate", return_value={"blocked": False, "warnings": []}), \\\n             patch("app.cycle.trading_phase.run_portfolio_allocator", new_callable=AsyncMock, side_effect=mock_alloc), \\\n             patch("app.cycle.trading_phase.run_trade_execution", new_callable=AsyncMock, return_value={"decision": "APPROVE", "shares": 0}), \\\n             patch("app.cycle.trading_phase.buy", new_callable=AsyncMock, return_value={"price": 300, "qty": 3, "amount": 900}), \\\n             patch("app.cycle.trading_phase.get_size_pct", return_value=0.10) as mock_size:\n    \n            res = await execute_decisions(decisions, cycle_id="cycle_mut3", bot_id="bot1")\n    \n        # Should have called fallback sizing\n        assert mock_size.called, f"Result was {res}"'

content = content.replace(target, replacement)

with open("tests/test_general_audit.py", "w") as f:
    f.write(content)
